string $moleculeScripts = "D:\\git\\mayaProgrammingB\\ch8_polygonalMeshes\\Molecule4";
string $newScriptPath=$moleculeScripts + ";" +`getenv "MAYA_SCRIPT_PATH"`;
putenv "MAYA_SCRIPT_PATH" $newScriptPath;

// origin test
loadPlugin "D:\\git\\mayaProgrammingB\\Release\\molecule4_origin.mll"
unloadPlugin -f molecule4_origin;


unloadPlugin Molecule4;
loadPlugin "D:\\git\\mayaProgrammingB\\Release\\Molecule4.mll";

molecule4;