global proc shelf_xxx () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -enable 1
        -width 35
        -height 35
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "#coding:utf-8\nimport xxSinglePyModule\nreload(xxSinglePyModule)\nxxSinglePyModule.main()" 
        -enableBackground 0
        -align "center" 
        -label "#coding:utf-8\nimport xxSinglePyModule\nreload(xxSinglePyModule)\nx..." 
        -labelOffset 0
        -font "plainLabelFont" 
        -imageOverlayLabel "win" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.2 
        -image "pythonFamily.png" 
        -image1 "pythonFamily.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "#coding:utf-8\nimport xxSinglePyModule\nreload(xxSinglePyModule)\nxxSinglePyModule.main()" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
